import = [
  "~/.config/alacritty/colors.toml"
]

[font]
size = 10.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window.padding]
x = 1
y = 1

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.8