[font]
size = 10.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window.padding]
x = 1
y = 1

[shell]
program = "/usr/bin/fish"

# Start flavours
# Base16 Generated 256 - alacritty color config
# Flavours

# Default colors
[colors.primary]
background = '0x331f43'
foreground = '0xeae3e6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x331f43'
cursor = '0xeae3e6'

# Normal colors
[colors.normal]
black = '0x331f43'
red = '0x8c69af'
green = '0xa76482'
yellow = '0xa26492'
blue = '0xcd4b61'
magenta = '0xae6079'
cyan = '0x787878'
white = '0xeae3e6'

# Bright colors
[colors.bright]
black = '0xa195a5'
red = '0x8c69af'
green = '0xa76482'
yellow = '0xa26492'
blue = '0xcd4b61'
magenta = '0xae6079'
cyan = '0x787878'
white = '0xf0ebee'

[[colors.indexed_colors]]
index = 16
color = "0x986c78"

[[colors.indexed_colors]]
index = 17
color = "0xd93e56"

[[colors.indexed_colors]]
index = 18
color = "0x574664"

[[colors.indexed_colors]]
index = 19
color = "0x7c6e84"

[[colors.indexed_colors]]
index = 20
color = "0xc6bcc6"

[[colors.indexed_colors]]
index = 21
color = "0xede7ea"
# End flavours
