#!/bin/sh

stowed() {
  dest=$1
  from=$2
  mkdir -p ${dest}
  stow -v -R -t ${dest} ${from}
}

echo ""
echo "Hallo, ${USER}. Konfiguration installieren."

stowed "${HOME}" home 
stowed "${HOME}/.config" config
stowed "${HOME}/.scripts" scripts
stowed "${HOME}/.config/fish/functions" fishes
echo ""
echo "Fertig."
