require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.autocmd"

require "user.telescope"
require "user.treesitter"
require "user.dashboard"
require "user.lualine"
require "user.cmp"
require "user.floaterm"
