require "my.options"
require "my.keymaps"
require "my.plugins"
require "my.colorscheme"
require "my.autocmd"

require "my.telescope"
require "my.treesitter"
require "my.writing"
require "my.lualine"
require "my.cmp"
require "my.lsp"
