[[items]]
name = "base16-sway"
path = "https://github.com/rkubosz/base16-sway"
themes-dir = "themes"
hook = "cp -f %f ~/.config/sway/config.d/theme && swaymsg reload"
[[items]]
name = "base16-waybar"
path = "https://github.com/tinted-theming/base16-waybar"
themes-dir = "colors"
hook = "cp -f %f ~/.config/waybar/colors.css"
[[items]]
name = "base16-mako"
path = "https://github.com/Eluminae/base16-mako"
themes-dir = "colors"
hook = "cp -f %f ~/.config/mako/config.d/theme && killall mako"
[[items]]
name = "base16-alacritty"
path = "https://github.com/aarowill/base16-alacritty"
themes-dir = "colors"
hook = "cp -f %f ~/.config/alacritty/colors.toml"
[[items]]
name = "base16-zathura"
path = "https://github.com/nicodebo/base16-zathura"
themes-dir = "build_schemes/colors"
hook = "cp -f %f ~/.config/zathura/themerc"
[[items]]
name = "base16-emacs"
path = "https://github.com/belak/base16-emacs"
themes-dir="build"
file-override = "$(tinty current)-theme"
hook = "cp -f %f ~/.emacs.d/custom-theme.el && emacsclient -e '(load-theme 'custom t)'"
[[items]]
name = "base16-rofi"
path = "https://gitlab.com/jordiorlando/base16-rofi"
themes-dir="colors"
hook = "cp -f %f ~/.config/rofi/colors.rasi"
